server:
  servlet:
    context-path: /honest
  port: 8080
  max-http-header-size: 102400000000
logging:
  level:
    root: debug
logging.level.com.xr.run.dao: debug
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 2000MB
      max-file-size: 2000MB
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:frontPage/,file:${file.uploadFolders}
      - /META-INF/resources/
      - /resources/
      - /public/
      - /frontPage/
      - /uploadimg/
      - /upload/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: xtycdflz
    #xtycdflz
    password: 123@xtycdflz
    #123@xtycdflz
    url: jdbc:mysql://10.73.100.46:3066/hanest?useSSL=false&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #url: jdbc:mysql://139.129.118.147:3306/hanest?useSSL=false&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis-plus:
  mapper-locations: mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
file:
  accessPath: /uploadimg/
  staticAccessPath: /uploadimg/**
  uploadFolder: D:/Tomcat8.5/webapps/hoonest/tmp/
  #uploadFolder: G:/Tomcat/apache-tomcat-9.0.19/webapps/hoonest/tmp/
  uploadDuty: D:/Tomcat8.5/webapps/hoonest/duty/
  #uploadDuty: G:/Tomcat/apache-tomcat-9.0.19/webapps/hoonest/duty/
  uploadImage: D:/Tomcat8.5/webapps/hoonest/img/
  #uploadImage: G:/Tomcat/apache-tomcat-9.0.19/webapps/hoonest/img/
  uploadVideo: D:/Tomcat8.5/webapps/hoonest/vido
  #uploadVideo: G:/Tomcat/apache-tomcat-9.0.19/webapps/hoonest/vido
  accessPaths: /upload
  staticAccessPaths: /upload/**
  uploadFolders: D:/Tomcat8.5/webapps/hoonest/img/
html:
  destPath: D:\tomcat\Tomcat8.5\webapps\honest\templates

